allowBlockBreak:
  toggle: false
  bypassPermission: "lobbycfg.blockbreakbypass"
  exceptions:
    - AIR
    - REDSTONE_BLOCK

allowBlockPlace:
  toggle: false
  bypassPermission: "lobbycfg.blockplacebypass"
  exceptions:
    - AIR
    - REDSTONE_BLOCK

allowInteract:
  toggle: false
  bypassPermission: "lobbycfg.interactbypass"
  exceptions:
      - ITEM_FRAME

allowPvp:
  toggle: false
  bypassPermission: "lobbycfg.pvpbypass"

allowDamage:
  toggle: true

allowHunger:
  toggle: true

playerMechanics:
  defaultGameMode: adventure
  # (x, y, z, yaw, pitch)
  spawnLocation: 0,81,0,90,0
  spawnWorld: world
  deathHeight: 30

allowedWorlds:
  - world
  - spawn
